version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - account_service
      - transaction_service

  account_service:
      build: .
      ports:
        - "8080:8080"
      environment:
        - DATABASE_HOST=db
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=example
        - DATABASE_NAME=mydb
        - DATABASE_PORT=5432
      depends_on:
        - db

  transaction_service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=mydb
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db_data:/var/lib/postgresql/data
      
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
