version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_server

  api_server:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    container_name: api_server
    expose:
      - "8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_PORT=5432
    volumes:
      - ./logs:/root/logs  # Mount a local directory for logs

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
