version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_server
  invalidator:
    build:
      context: .
      dockerfile: Dockerfile.invalidator
    container_name: invalidator
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_PORT=5432
      - MODULDE=invalidator
    volumes:
      - ./invalidator_logs:/var/log/invalidator
    depends_on:
      db:
        condition: service_healthy
  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server
    expose:
      - "8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_PORT=5432
      - MODULDE=api
    volumes:
      - ./api_logs:/var/log/api
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
  namesrv:
    image: apache/rocketmq:4.9.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
    networks:
      - rocketmq-net
  broker:
    image: apache/rocketmq:4.9.1
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    command: sh mqbroker -n namesrv:9876 -c /etc/rocketmq/broker.conf
    volumes:
      - ./broker.conf:/etc/rocketmq/broker.conf
    depends_on:
      - namesrv
    networks:
      - rocketmq-net
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - namesrv
      - broker
    networks:
      - rocketmq-net

networks:
  rocketmq-net:
    driver: bridge
volumes:
  db_data:
  redis_data: