# Build stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o bin/invalidator ./cmd/invalidator/main.go


# Final stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/bin/invalidator /usr/local/bin/invalidator

RUN mkdir -p /var/log/invalidator
COPY config/ ./


CMD ["invalidator"]